// <auto-generated />
using BilvisionTennisAPI.GraphQL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BilvisionTennisAPI.GraphQL.Migrations
{
    [DbContext(typeof(TennisDbContext))]
    [Migration("20251029153753_FixedUmpireMatchConnection")]
    partial class FixedUmpireMatchConnection
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BilvisionTennisAPI.GraphQL.Data.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("MatchId")
                        .HasColumnType("integer");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("BilvisionTennisAPI.GraphQL.Data.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("UmpireId")
                        .HasColumnType("integer");

                    b.Property<int?>("WInnerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UmpireId");

                    b.HasIndex("WInnerId");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("BilvisionTennisAPI.GraphQL.Data.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("BilvisionTennisAPI.GraphQL.Data.Rally", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ScorerId")
                        .HasColumnType("integer");

                    b.Property<int?>("SetId")
                        .HasColumnType("integer");

                    b.Property<int>("ShotNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ScorerId");

                    b.HasIndex("SetId");

                    b.ToTable("Rallies");
                });

            modelBuilder.Entity("BilvisionTennisAPI.GraphQL.Data.Set", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("GameId")
                        .HasColumnType("integer");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("Sets");
                });

            modelBuilder.Entity("BilvisionTennisAPI.GraphQL.Data.Umpire", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Umpires");
                });

            modelBuilder.Entity("MatchPlayer", b =>
                {
                    b.Property<int>("MatchesId")
                        .HasColumnType("integer");

                    b.Property<int>("PlayersId")
                        .HasColumnType("integer");

                    b.HasKey("MatchesId", "PlayersId");

                    b.HasIndex("PlayersId");

                    b.ToTable("MatchPlayer");
                });

            modelBuilder.Entity("BilvisionTennisAPI.GraphQL.Data.Game", b =>
                {
                    b.HasOne("BilvisionTennisAPI.GraphQL.Data.Match", null)
                        .WithMany("Games")
                        .HasForeignKey("MatchId");
                });

            modelBuilder.Entity("BilvisionTennisAPI.GraphQL.Data.Match", b =>
                {
                    b.HasOne("BilvisionTennisAPI.GraphQL.Data.Umpire", "Umpire")
                        .WithMany("Matches")
                        .HasForeignKey("UmpireId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BilvisionTennisAPI.GraphQL.Data.Player", "Winner")
                        .WithMany("WonMatches")
                        .HasForeignKey("WInnerId");

                    b.Navigation("Umpire");

                    b.Navigation("Winner");
                });

            modelBuilder.Entity("BilvisionTennisAPI.GraphQL.Data.Rally", b =>
                {
                    b.HasOne("BilvisionTennisAPI.GraphQL.Data.Player", "Scorer")
                        .WithMany()
                        .HasForeignKey("ScorerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BilvisionTennisAPI.GraphQL.Data.Set", null)
                        .WithMany("Rallies")
                        .HasForeignKey("SetId");

                    b.Navigation("Scorer");
                });

            modelBuilder.Entity("BilvisionTennisAPI.GraphQL.Data.Set", b =>
                {
                    b.HasOne("BilvisionTennisAPI.GraphQL.Data.Game", null)
                        .WithMany("Sets")
                        .HasForeignKey("GameId");
                });

            modelBuilder.Entity("MatchPlayer", b =>
                {
                    b.HasOne("BilvisionTennisAPI.GraphQL.Data.Match", null)
                        .WithMany()
                        .HasForeignKey("MatchesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BilvisionTennisAPI.GraphQL.Data.Player", null)
                        .WithMany()
                        .HasForeignKey("PlayersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BilvisionTennisAPI.GraphQL.Data.Game", b =>
                {
                    b.Navigation("Sets");
                });

            modelBuilder.Entity("BilvisionTennisAPI.GraphQL.Data.Match", b =>
                {
                    b.Navigation("Games");
                });

            modelBuilder.Entity("BilvisionTennisAPI.GraphQL.Data.Player", b =>
                {
                    b.Navigation("WonMatches");
                });

            modelBuilder.Entity("BilvisionTennisAPI.GraphQL.Data.Set", b =>
                {
                    b.Navigation("Rallies");
                });

            modelBuilder.Entity("BilvisionTennisAPI.GraphQL.Data.Umpire", b =>
                {
                    b.Navigation("Matches");
                });
#pragma warning restore 612, 618
        }
    }
}
